### ISSUE TITLE
SSL certificate about to expire on biojs1.stemformatics.org

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#34]
I have received this email today:

```
Hello,

Your certificate (or certificates) for the names listed below will expire in
1 days (on 16 May 18 23:28 +0000). Please make sure to renew
your certificate before then, or visitors to your website will encounter errors.

biojs1.stemformatics.org

For any questions or support, please visit https://community.letsencrypt.org/.
Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit
https://letsencrypt.org/docs/expiration-emails/. In particular, note
that this reminder email is still sent if you've obtained a slightly
different certificate by adding or removing names. If you've replaced
this certificate with a newer one that covers more or fewer names than
the list above, you may be able to ignore this message.

If you want to stop receiving all email from this address, click
http://mandrillapp.com/track/unsub.php?u=30850198&id=1632553095a84bb78d9e7d56924b8d21.NF9VoQxsrVs97KGlCed1%2FyvMilQ%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dschwartz_dennis%2540web.de
(Warning: this is a one-click action that cannot be undone)

Regards,
The Let's Encrypt Team
```

Does anyone know how we got the certificate in the first place? And if this could be a problem? 
The workman is running on biojs3 at the moment anyway.

**Comment by Megh-Thakkar** [comment]
Let's encrypt works on a service called certbot. Afaik, running 
```shell
$ sudo certbot renew 
```
will renew all the ssl certificates on the server system.

A while ago, I saw a blog post that said that Lets Encrypt had put a halt on providing ssl certificates. You would might like to have a look on that.

**Comment by DennisSchwartz** [comment]
Thanks @Megh-Thakkar! I was going through the console history an couldn't find certbot anywhere which is why I asked here.

I just ran it now and it's throwing an error:

```
dennis@biojs1:~$ sudo certbot renew
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 833, in main
    log.pre_arg_parse_setup()
  File "/usr/lib/python2.7/dist-packages/certbot/log.py", line 55, in pre_arg_parse_setup
    temp_handler = TempHandler()
  File "/usr/lib/python2.7/dist-packages/certbot/log.py", line 264, in __init__
    stream = tempfile.NamedTemporaryFile('w', delete=False)
  File "/usr/lib/python2.7/tempfile.py", line 463, in NamedTemporaryFile
    dir = gettempdir()
  File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/dennis']
```

Not even sure we need the certificate at this point. 🤔

**Comment by rowlandm** [comment]
I'm not getting anything on:
https://biojs3.stemformatics.org/

**Comment by Megh-Thakkar** [comment]
@DennisSchwartz can you make sure you have the required root permissions? Check out the first answer [here](https://stackoverflow.com/questions/16996125/no-usable-temporary-directory-found)

**Comment by DennisSchwartz** [comment]
Thanks again! It was actually the disk space that was missing :)

```
Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/biojs1.stemformatics.org/fullchain.pem (success)
```
